-- Run on a dedicated Dolce Look database, never on another application's project.
begin;
create schema if not exists dolce_private;
revoke all on schema dolce_private from public,anon,authenticated;
create table dolce_private.admins(user_id uuid primary key references auth.users(id) on delete cascade);
create function public.dolce_is_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from dolce_private.admins where user_id=auth.uid()) $$;
revoke all on function public.dolce_is_admin() from public,anon;
grant execute on function public.dolce_is_admin() to authenticated;
create table public.dolce_products (
 id bigint generated by default as identity primary key,
 name text not null check(length(name) between 1 and 140),
 type text not null check(type in ('Camisas','Blusas','Conjuntos','Vestidos')),
 "desc" text not null,
 img text not null,
 size text, price numeric(12,2) check(price>=0),
 status text not null default 'draft' check(status in ('draft','available','sold','hidden')),
 stock smallint not null default 0 check(stock in (0,1)),
 version bigint not null default 1,
 updated_at timestamptz not null default now(),
 sold_at timestamptz,
 check ((status='available' and stock=1) or (status<>'available' and stock=0))
);
alter table public.dolce_products enable row level security;
grant select on public.dolce_products to anon,authenticated;
grant insert,update,delete on public.dolce_products to authenticated;
grant usage,select on sequence public.dolce_products_id_seq to authenticated;
create policy "Available pieces" on public.dolce_products for select to anon,authenticated using(status='available');
create policy "Admin reads all" on public.dolce_products for select to authenticated using(public.dolce_is_admin());
create policy "Admin inserts" on public.dolce_products for insert to authenticated with check(public.dolce_is_admin());
create policy "Admin updates" on public.dolce_products for update to authenticated using(public.dolce_is_admin()) with check(public.dolce_is_admin());
create policy "Admin deletes" on public.dolce_products for delete to authenticated using(public.dolce_is_admin());
create table public.dolce_audit(id bigint generated always as identity primary key, product_id bigint not null, actor uuid, action text not null, created_at timestamptz not null default now());
alter table public.dolce_audit enable row level security;
grant select on public.dolce_audit to authenticated;
create policy "Admin history" on public.dolce_audit for select to authenticated using(public.dolce_is_admin());
create table public.dolce_inventory_revision(id smallint primary key check(id=1),revision bigint not null default 0);
insert into public.dolce_inventory_revision values(1,0);
alter table public.dolce_inventory_revision enable row level security;
grant select on public.dolce_inventory_revision to anon,authenticated;
create policy "Public refresh signal" on public.dolce_inventory_revision for select to anon,authenticated using(true);
create function dolce_private.before_product() returns trigger language plpgsql set search_path='' as $$ begin
 new.stock:=case when new.status='available' then 1 else 0 end;
 new.updated_at:=now();
 if TG_OP='UPDATE' then new.version:=old.version+1; end if;
 new.sold_at:=case when new.status='sold' then coalesce(new.sold_at,now()) else null end;
 return new;
end $$;
create trigger normalize_product before insert or update on public.dolce_products for each row execute function dolce_private.before_product();
create function dolce_private.after_product() returns trigger language plpgsql security definer set search_path='' as $$ begin
 insert into public.dolce_audit(product_id,actor,action) values(coalesce(new.id,old.id),auth.uid(),case when TG_OP='UPDATE' then old.status||' → '||new.status else TG_OP end);
 update public.dolce_inventory_revision set revision=revision+1 where id=1;
 return coalesce(new,old);
end $$;
create trigger product_history after insert or update or delete on public.dolce_products for each row execute function dolce_private.after_product();
create function public.dolce_set_status(product_id bigint,expected_version bigint,next_status text) returns void language plpgsql security invoker set search_path='' as $$ begin
 if not public.dolce_is_admin() then raise exception 'Access denied'; end if;
 if next_status not in ('available','sold','hidden') then raise exception 'Invalid status'; end if;
 update public.dolce_products set status=next_status where id=product_id and version=expected_version and (next_status<>'sold' or status='available');
 if not found then raise exception 'Product changed; refresh and retry'; end if;
end $$;
revoke all on function public.dolce_set_status(bigint,bigint,text) from public;
grant execute on function public.dolce_set_status(bigint,bigint,text) to authenticated;
alter publication supabase_realtime add table public.dolce_inventory_revision;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('dolce-media','dolce-media',true,8388608,array['image/jpeg','image/png','image/webp']);
create policy "Admin uploads Dolce images" on storage.objects for insert to authenticated with check(bucket_id='dolce-media' and public.dolce_is_admin());
create policy "Admin manages Dolce images" on storage.objects for all to authenticated using(bucket_id='dolce-media' and public.dolce_is_admin()) with check(bucket_id='dolce-media' and public.dolce_is_admin());
create table dolce_private.admin_setup(token_hash text primary key, email text not null, expires_at timestamptz not null default now()+interval '7 days', claimed_at timestamptz);
create function public.dolce_claim_setup(p_hash text) returns text language plpgsql security definer set search_path='' as $$ declare owner_email text; begin
 update dolce_private.admin_setup set claimed_at=now() where token_hash=p_hash and claimed_at is null and expires_at>now() returning email into owner_email;
 return owner_email;
end $$;
create function public.dolce_finish_setup(p_user uuid) returns void language sql security definer set search_path='' as $$ insert into dolce_private.admins(user_id) values(p_user) $$;
create function public.dolce_retry_setup(p_hash text) returns void language sql security definer set search_path='' as $$ update dolce_private.admin_setup set claimed_at=null where token_hash=p_hash $$;
revoke all on function public.dolce_claim_setup(text),public.dolce_finish_setup(uuid),public.dolce_retry_setup(text) from public,anon,authenticated;
grant execute on function public.dolce_claim_setup(text),public.dolce_finish_setup(uuid),public.dolce_retry_setup(text) to service_role;
revoke insert,update,delete,truncate,references,trigger on public.dolce_audit,public.dolce_inventory_revision from anon,authenticated;
commit;
-- Create/invite the owner's Auth account privately, then grant access with:
-- insert into dolce_private.admins(user_id) values('<verified Auth user uuid>');
-- Keep public sign-ups disabled. Never put a service role key in the frontend.
