import {useEffect,useState} from 'react';
import {db,availableSizes,allSizeStock,GARMENT_SIZES,notifyInventory,type Look,type GarmentSize} from './inventory';
import type {Session} from '@supabase/supabase-js';
import './admin.css';
const setupToken=new URLSearchParams(location.hash.slice(1)).get('setup')||'';
if(setupToken)history.replaceState(null,'','/admin');
const blank={name:'',type:'Blusas',desc:'',img:'',price:'',status:'draft',size_stock:allSizeStock()};
const labels:Record<string,string>={available:'Na vitrine',sold:'Vendido',draft:'Rascunho',hidden:'Oculto'};
function historyLabel(action:string){const [state,stock]=action.split(' · tamanhos: ');const label=state.replaceAll('available','disponível').replaceAll('sold','vendido').replaceAll('hidden','oculto').replaceAll('draft','rascunho').replaceAll('INSERT','Peça cadastrada').replaceAll('DELETE','Peça removida');if(!stock)return label;try{const sizes=JSON.parse(stock);return label+' · '+GARMENT_SIZES.map(size=>size+': '+(sizes[size]?'disponível':'esgotado')).join(' · ');}catch{return label;}}
function Arrow(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>}
function Brand(){return <img className="admin-logo" src="/media/logo.webp" alt="Dolce Look by Josy"/>}
export function Admin(){
 const [setup,setSetup]=useState(!!setupToken),[session,setSession]=useState<Session|null>(null),[allowed,setAllowed]=useState(false),[ready,setReady]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[rows,setRows]=useState<Look[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<Look|null>(null),[form,setForm]=useState(blank),[editing,setEditing]=useState(false),[history,setHistory]=useState<{created_at:string;product_id:number;action:string}[]>([]),[tab,setTab]=useState('available'),[sizeFilter,setSizeFilter]=useState('Todos'),[query,setQuery]=useState('');
 async function load(){if(!db)return;const {data,error}=await db.from('dolce_products').select('*').order('id');if(error){setMessage('Não conseguimos atualizar o estoque. Tente novamente.');return;}setRows(data||[]);const audit=await db.from('dolce_audit').select('created_at,product_id,action').order('created_at',{ascending:false}).limit(40);setHistory(audit.data||[]);}
 useEffect(()=>{if(!db)return;let alive=true;async function authorize(s:Session|null){if(!alive)return;setSession(s);setAllowed(false);if(s){const {data}=await db!.rpc('dolce_is_admin');if(alive){setAllowed(data===true);if(data===true)void load();}}if(alive)setReady(true);}void db.auth.getSession().then(({data})=>authorize(data.session));const {data}=db.auth.onAuthStateChange((_event,s)=>{setTimeout(()=>void authorize(s),0);});return()=>{alive=false;data.subscription.unsubscribe();};},[]);
 useEffect(()=>{if(!allowed||!db)return;const channel=db.channel('dolce-admin-stock').on('postgres_changes',{event:'*',schema:'public',table:'dolce_inventory_revision'},()=>void load()).subscribe();const poll=setInterval(()=>void load(),4000);return()=>{clearInterval(poll);void db!.removeChannel(channel);};},[allowed]);
 async function activate(e:React.FormEvent){e.preventDefault();if(!db)return;setBusy(true);const {error}=await db.functions.invoke('dolce-admin-setup',{body:{token:setupToken,password}});setPassword('');setMessage(error?'Não foi possível criar o acesso. Confira o link e use uma senha de pelo menos 12 caracteres.':'Acesso criado. Entre com seu e-mail e senha.');if(!error){setSetup(false);setEmail('michaeldouggmarketing@gmail.com');}setBusy(false);}
 async function login(e:React.FormEvent){e.preventDefault();if(!db)return;setBusy(true);const {error}=await db.auth.signInWithPassword({email,password});setPassword('');setMessage(error?'Não foi possível entrar. Confira seu e-mail e sua senha.':'');setBusy(false);}
 async function status(l:Look,next:string){if(!db)return;setBusy(true);const {error}=await db.rpc('dolce_set_status',{product_id:l.id,expected_version:l.version,next_status:next});setMessage(error?'O estoque mudou. Atualizei os dados; tente novamente.':next==='sold'?'Peça vendida e guardada no histórico.':'Peça restaurada e sincronizada com a vitrine.');if(!error)notifyInventory();await load();setBusy(false);}
 async function sizeStatus(l:Look,size:GarmentSize,is_available:boolean){if(!db)return;setBusy(true);const {error}=await db.rpc('dolce_set_size_stock',{product_id:l.id,expected_version:l.version,garment_size:size,is_available});setMessage(error?'O estoque mudou. Atualizei os dados; tente novamente.':`${l.name} · ${size}: ${is_available?'restaurado':'vendido'}. Vitrine sincronizada.`);if(!error)notifyInventory();await load();setBusy(false);}
 async function save(e:React.FormEvent){e.preventDefault();if(!db)return;if(form.status==='available'&&!Object.values(form.size_stock).some(Boolean)){setMessage('Selecione pelo menos um tamanho disponível para publicar.');return;}setBusy(true);const payload={...form,size:null,price:form.price?Number(form.price):null};const result=edit?await db.from('dolce_products').update(payload).eq('id',edit.id).eq('version',edit.version).select('id'):await db.from('dolce_products').insert(payload).select('id');if(result.error||!result.data?.length)setMessage('Não foi possível salvar. Atualize os dados e tente novamente.');else{setEditing(false);setMessage('Peça salva e sincronizada.');notifyInventory();await load();}setBusy(false);}
 async function upload(file:File){if(!db)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setMessage('Use JPG, PNG ou WebP até 8 MB.');return;}setBusy(true);const path=`products/${crypto.randomUUID()}.${file.type.split('/')[1]}`;const {error}=await db.storage.from('dolce-media').upload(path,file);if(error)setMessage('Não foi possível enviar a imagem.');else setForm(f=>({...f,img:db!.storage.from('dolce-media').getPublicUrl(path).data.publicUrl}));setBusy(false);}
 function openEditor(l?:Look){setEdit(l||null);setForm(l?{name:l.name,type:l.type,desc:l.desc,img:l.img,price:l.price?.toString()||'',status:l.status||'draft',size_stock:l.size_stock||allSizeStock()}:({...blank,size_stock:allSizeStock()}));setEditing(true);}
 const visible=rows.filter(l=>(tab==='all'||l.status===tab)&&l.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))&&(sizeFilter==='Todos'||(tab==='sold'?!l.size_stock?.[sizeFilter as GarmentSize]:availableSizes(l).includes(sizeFilter as GarmentSize))));
 const active=session&&allowed;
 return <div className={'admin dolce-admin '+(active?'is-authenticated':'is-login')}><aside className="admin-sidebar"><a href="/" aria-label="Dolce Look — visitar site"><Brand/></a><p>By Josy<br/><span>Seu estilo. Sua coleção.</span></p>{active&&<><nav aria-label="Áreas do Admin"><button className={tab==='available'?'active':''} onClick={()=>{setTab('available');setEditing(false);}}>Sua coleção <Arrow/></button><button className={tab==='sold'?'active':''} onClick={()=>{setTab('sold');setEditing(false);}}>Vendidos e restauração <Arrow/></button><button className={tab==='all'?'active':''} onClick={()=>{setTab('all');setEditing(false);}}>Todas as peças <Arrow/></button></nav><div className="admin-sidebar-bottom"><a href="/" target="_blank" rel="noreferrer">Ver meu site <Arrow/></a><button onClick={()=>void db?.auth.signOut()}>Sair da minha loja</button></div></>}</aside>
 <main className="admin-main">{!db?<div className="admin-login"><h1>Sua loja, por perto.</h1><p>A conexão do estoque está indisponível. Tente novamente mais tarde.</p><a className="admin-button" href="/">Voltar ao site</a></div>:!ready?<p role="status">Verificando seu acesso…</p>:!session?<form className="admin-login" onSubmit={setup?activate:login}><div className="admin-login-mark"><Brand/></div><h1>{setup?'Seu espaço Dolce Look.':'Bem-vinda, Josy.'}</h1><p>{setup?'Crie sua senha para cuidar da coleção.':'Sua coleção, seus tamanhos e suas vendas. Tudo em um só lugar.'}</p>{!setup&&<label>E-mail<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}<label>{setup?'Crie sua senha':'Senha'}<input type="password" autoComplete={setup?'new-password':'current-password'} minLength={setup?12:undefined} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="admin-button" disabled={busy}>{busy?'Aguarde…':setup?'Criar meu acesso':'Entrar na minha loja'}<Arrow/></button>{setup&&<button type="button" className="admin-text-button" onClick={()=>setSetup(false)}>Já tenho acesso</button>}<a className="admin-back" href="/">Voltar para o site Dolce Look</a></form>:!allowed?<div className="admin-login"><h1>Acesso não autorizado.</h1><p>Esta conta ainda não foi liberada para administrar a Dolce Look.</p><button className="admin-button" onClick={()=>void db?.auth.signOut()}>Trocar de conta</button></div>:<>
 <header className="admin-heading"><div><h1>{tab==='sold'?'Cada peça tem uma história.':'Sua coleção, seu olhar.'}</h1><p>{tab==='sold'?'As peças vendidas ficam guardadas aqui. Restaure somente os tamanhos que voltaram.':'Cuide dos looks e dos tamanhos disponíveis na sua loja.'}</p></div><button className="admin-button" onClick={()=>openEditor()}>Cadastrar peça <span aria-hidden="true">+</span></button></header>
 <div className="admin-overview"><p><strong>{rows.filter(l=>l.status==='available').length}</strong> looks na vitrine</p><p><strong>{rows.filter(l=>l.status==='sold').length}</strong> looks vendidos</p><a href="/" target="_blank" rel="noreferrer">Minha vitrine <Arrow/></a></div>
 {editing&&<form className="admin-editor" onSubmit={save}><div className="admin-editor-title"><h2>{edit?'Cuidar desta peça':'Um novo look'}</h2><button type="button" className="admin-text-button" onClick={()=>setEditing(false)}>Fechar</button></div><label>Nome da peça<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Categoria<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['Camisas','Blusas','Conjuntos','Vestidos'].map(t=><option key={t}>{t}</option>)}</select></label><label>Descrição<textarea required value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})}/></label><fieldset className="admin-size-editor"><legend>Tamanhos disponíveis</legend><div>{GARMENT_SIZES.map(size=><label key={size}><input type="checkbox" checked={form.size_stock[size]} onChange={e=>setForm({...form,size_stock:{...form.size_stock,[size]:e.target.checked}})}/>{size}</label>)}</div></fieldset><label>Preço (R$)<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Foto da peça<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/></label>{form.img&&<img className="admin-preview" src={form.img} alt="Prévia da peça"/>}<label>Publicação<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Rascunho</option><option value="available">Na vitrine</option><option value="hidden">Oculto</option>{edit?.status==='sold'&&<option value="sold">Vendido</option>}</select></label><div className="admin-editor-actions"><button className="admin-button" disabled={busy||!form.img}>Salvar peça <Arrow/></button><button type="button" className="admin-text-button" onClick={()=>setEditing(false)}>Cancelar</button></div></form>}
 <div className="admin-filters"><div className="admin-tabs" aria-label="Filtrar peças">{[['available','Na vitrine'],['sold','Vendidos'],['all','Todas']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div><label><span className="sr-only">Buscar no estoque</span><input type="search" placeholder="Buscar uma peça" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span className="sr-only">Filtrar estoque por tamanho</span><select value={sizeFilter} onChange={e=>setSizeFilter(e.target.value)}><option value="Todos">Todos os tamanhos</option>{GARMENT_SIZES.map(size=><option key={size} value={size}>Tamanho {size}</option>)}</select></label></div>
 <div className="admin-products">{visible.map(l=><article key={l.id}><img src={l.img} alt={l.name}/><div className="admin-piece-copy"><span className={'admin-status status-'+l.status}>{labels[l.status||'draft']}</span><h2>{l.name}</h2><p>{l.type}{l.sold_at?` · Vendido em ${new Date(l.sold_at).toLocaleDateString('pt-BR')}`:''}</p><div className="admin-stock-sizes" aria-label={`Estoque por tamanho de ${l.name}`}>{GARMENT_SIZES.map(size=>{const present=l.size_stock?.[size]??availableSizes(l).includes(size);return <div key={size} className={present?'in-stock':'out-stock'}><strong>{size}</strong><span>{present?'Disponível':'Esgotado'}</span><button disabled={busy} onClick={()=>void sizeStatus(l,size,!present)} aria-label={`${present?'Vendido':'Restaurar'} tamanho ${size} de ${l.name}`}>{present?'Vendido':'Restaurar'}</button></div>;})}</div></div><div className="admin-actions"><button className="admin-edit-button" disabled={busy} onClick={()=>openEditor(l)}>Editar peça</button>{l.status==='available'?<button className="admin-sell-button" disabled={busy} onClick={()=>void status(l,'sold')}>Vendido · todos os tamanhos</button>:<button className="admin-restore-button" disabled={busy} onClick={()=>void status(l,'available')}>{l.status==='sold'?'Restaurar todos os tamanhos':'Publicar peça'}</button>}</div></article>)}</div>{!visible.length&&<div className="admin-empty"><h2>{tab==='sold'?'Novas histórias virão.':'Nenhuma peça por aqui.'}</h2><p>{tab==='sold'?'As peças esgotadas vão aparecer aqui, prontas para serem restauradas quando voltarem.':'Experimente outro tamanho ou outra busca.'}</p></div>}
 <section className="admin-history"><h2>Diário da sua loja</h2><p>Vendas, alterações de tamanho e restaurações ficam registradas.</p>{history.map((h,i)=><div key={i}><time>{new Date(h.created_at).toLocaleString('pt-BR')}</time><span>{rows.find(l=>l.id===h.product_id)?.name||`Peça ${h.product_id}`}</span><p>{historyLabel(h.action)}</p></div>)}</section></>}
 <p role="status" className="admin-message">{message}</p></main></div>;
}
