import{useEffect,useRef,useState}from'react';
import './premium.css';
import MagazineShelf from './MagazineShelf';
import HeroPhoto from './HeroPhoto';
import LookMedia from './LookMedia';
import {UNIVERSE_LOOK_VIDEOS_ENABLED} from './motion-settings';
import gsap from 'gsap';import{ScrollTrigger}from'gsap/ScrollTrigger';import Lenis from 'lenis';
import{useInventory,type Look}from'./inventory';
gsap.registerPlugin(ScrollTrigger);
export const wa=(s:string)=>`https://wa.me/5535998290565?text=${encodeURIComponent(s)}`;
function Icon({name='arrow'}:{name?:'arrow'|'heart'|'menu'|'close'|'whatsapp'|'down'}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{name==='heart'?<path d="M12 20 3.5 11.8A5.3 5.3 0 0 1 12 4.9a5.3 5.3 0 0 1 8.5 6.9Z"/>:name==='menu'?<><path d="M3 8h18M3 16h18"/></>:name==='close'?<path d="m5 5 14 14M19 5 5 19"/>:name==='down'?<path d="M12 4v16m-6-6 6 6 6-6"/>:name==='whatsapp'?<><path d="M20.4 11.6a8.4 8.4 0 0 1-12.5 7.3L3 20l1.2-4.7A8.4 8.4 0 1 1 20.4 11.6Z"/><path d="M8 7.5c-.9 1.4-.4 3.2 1.9 5.4 2.2 2.2 4 2.7 5.4 1.8l.9-1.5-2.4-1.2-1 1c-1.4-.7-2.4-1.7-3.1-3l1-1L9.5 6.6Z"/></>:<path d="M5 19 19 5M5 5h14v14"/>}</svg>}
function Button({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <a className={'action '+(light?'light':'')} href={href} {...(href.startsWith('https://')?{target:'_blank',rel:'noreferrer'}:{})}><span>{children}</span><Icon/></a>}
function Photo({look,className='',priority=false,motion=false}:{look?:Look;className?:string;priority?:boolean;motion?:boolean}){return <figure className={'photo '+className}><LookMedia look={look} priority={priority} alwaysAnimate={motion} key={`${look?.id}:${look?.img}`}/></figure>}
function useChoreography(root:React.RefObject<HTMLDivElement|null>,signature:string){useEffect(()=>{const ambient=Array.from(root.current?.querySelectorAll<HTMLElement>('.hero-glow,.fashion-ticker,.contact-arc,.atelier-light,.luminous-type')||[]);const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('ambient-visible',e.isIntersecting)));ambient.forEach(e=>observer.observe(e));const visibility=()=>root.current?.classList.toggle('motion-paused',document.hidden);document.addEventListener('visibilitychange',visibility);const ctx=gsap.context(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const lenis=new Lenis({duration:.75,smoothWheel:true,syncTouch:false});const tick=(time:number)=>lenis.raf(time*1000);lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(tick);
 const hero=document.querySelector('.cinema');if(hero){const mobile=innerWidth<760;const tl=gsap.timeline({scrollTrigger:{trigger:hero,start:'top top',end:mobile?'+=680':'+=1150',pin:true,scrub:.3,invalidateOnRefresh:true}});
 tl.to('.hero-frame.center',{scale:mobile?1.1:1.28,y:mobile?-35:-60,rotate:0,duration:1},0).to('.hero-frame.left',{xPercent:-32,yPercent:20,rotate:-13,scale:.9,duration:1},0).to('.hero-frame.right',{xPercent:35,yPercent:-17,rotate:13,scale:.92,duration:1},0).to('.hero-headline',{yPercent:-36,opacity:.25,duration:1},0).to('.hero-promise',{y:-26,opacity:0,duration:.45},0).fromTo('.hero-after',{y:35,opacity:0},{y:0,opacity:1,duration:.6},.45).to('.hero-glow',{xPercent:35,scale:1.4,duration:1},0).to('.scene-progress span',{scaleX:1,duration:1},0);
 gsap.from('.hero-frame',{clipPath:'inset(18% 0% 18% 0%)',duration:1.05,stagger:.12,ease:'expo.out'});gsap.from('.hero-headline .line span',{yPercent:105,duration:.95,stagger:.1,ease:'expo.out'});
 }
 const chapter=document.querySelector('.wardrobe');if(chapter){const mobile=innerWidth<760;const panels=gsap.utils.toArray<HTMLElement>('.wardrobe-panel');if(panels.length>1){panels.forEach((p,i)=>gsap.set(p,{zIndex:i+1}));gsap.set(panels.slice(1),{clipPath:'inset(100% 0 0 0)',visibility:'hidden'});const tl=gsap.timeline({scrollTrigger:{trigger:chapter,start:'top top',end:()=>'+='+((mobile?850:1050)*(panels.length-1)),pin:true,scrub:.18,invalidateOnRefresh:true}});tl.to({}, {duration:.35});panels.slice(1).forEach((p,i)=>{const at=.35+i*1.8;const previous=panels[i];tl.to(previous.querySelector('.wardrobe-copy'),{y:-24,opacity:0,duration:.25,ease:'power2.in'},at).set(p,{visibility:'visible'},at+.25).to(p,{clipPath:'inset(0% 0 0 0)',duration:.85,ease:'none'},at+.25).fromTo(p.querySelector('.wardrobe-image'),{yPercent:100},{yPercent:0,duration:.85,ease:'power2.out'},at+.25).to(previous.querySelector('.wardrobe-image'),{yPercent:-12,scale:1.04,duration:.85,ease:'none'},at+.25).fromTo(p.querySelector('.wardrobe-copy'),{y:28,opacity:0},{y:0,opacity:1,duration:.35,ease:'expo.out'},at+1.05);});tl.to({}, {duration:.4});}}
 const entrance=(target:string,from:gsap.TweenVars,trigger?:string)=>gsap.utils.toArray<HTMLElement>(target).forEach(el=>gsap.from(el,{...from,duration:.9,ease:'expo.out',scrollTrigger:{trigger:trigger||el,start:'top 91%',once:true}}));
 entrance('[data-reveal]:not(h2)',{y:35,clipPath:'inset(12% 0 0 0)'});
 entrance('.section-top h2,.josy-preview h2,.brand-service h2,.service-steps h2,.faq h2',{y:38,clipPath:'inset(0 0 100% 0)'});
 entrance('.catalogue-intro h1,.brand-intro h1,.contact-intro h1,.detail-content h1,.empty-state h1',{x:-32,opacity:0});
 entrance('.editorial-top h2,.brand-diptych h2',{x:38,opacity:0});
 entrance('.contact-scene h2',{y:48,scale:.96,opacity:0});
 entrance('.universe-copy>p,.universe-copy>.underlined,.section-top>div,.josy-preview>div>p,.josy-preview .action,.brand-story-copy,.brand-service>div,.contact-intro p,.contact-intro .action,.detail-content>p,.detail-content dl,.faq>div',{x:22,opacity:0,duration:.65});
 gsap.utils.toArray<HTMLElement>('.service-steps li').forEach((el,i)=>gsap.from(el,{y:30,opacity:0,delay:i*.08,duration:.7,ease:'expo.out',scrollTrigger:{trigger:el,start:'top 92%',once:true}}));
 gsap.utils.toArray<HTMLElement>('.product-card').forEach((el,i)=>gsap.from(el,{y:i%2?55:30,clipPath:'inset(8% 0 0 0)',opacity:0,duration:.8,ease:'expo.out',scrollTrigger:{trigger:el,start:'top 95%',once:true}}));
 gsap.utils.toArray<HTMLElement>('.parallax').forEach(el=>gsap.fromTo(el.querySelectorAll('img,video'),{yPercent:-5,scale:1.12},{yPercent:5,scale:1.12,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:true}}));
 gsap.utils.toArray<HTMLElement>('.word-flow').forEach(el=>gsap.fromTo(el.querySelectorAll('span'),{opacity:.28},{opacity:1,stagger:.12,ease:'none',scrollTrigger:{trigger:el,start:'top 86%',end:'bottom 60%',scrub:true}}));
 gsap.utils.toArray<HTMLElement>('.universe-visual,.josy-preview>.photo,.brand-portrait,.contact-photo,.brand-diptych>.photo,.detail-photo').forEach(el=>gsap.fromTo(el,{clipPath:'inset(12% 0 12% 0)',rotate:-2},{clipPath:'inset(0% 0 0% 0)',rotate:1,ease:'none',scrollTrigger:{trigger:el,start:'top 98%',end:'top 30%',scrub:.35}}));
 entrance('.site-footer .brand-word',{y:35,opacity:0});
 entrance('.site-footer nav,.footer-social',{x:20,opacity:0});
 const rail=document.querySelector<HTMLElement>('.editorial-track');if(rail&&innerWidth>=900){gsap.to(rail,{x:()=>Math.min(0,-(rail.scrollWidth-innerWidth)),ease:'none',scrollTrigger:{trigger:'.editorial',start:'top top',end:()=>'+='+Math.max(500,rail.scrollWidth-innerWidth),pin:true,scrub:.25,invalidateOnRefresh:true}})}
 gsap.utils.toArray<HTMLElement>('.expand-panel').forEach(el=>gsap.fromTo(el,{clipPath:'inset(6% 6% 6% 6%)'},{clipPath:'inset(0% 0% 0% 0%)',ease:'none',scrollTrigger:{trigger:el,start:'top 95%',end:'center center',scrub:true}}));
 return()=>{gsap.ticker.remove(tick);lenis.destroy()};});},root);const refresh=()=>ScrollTrigger.refresh();window.addEventListener('load',refresh);const timer=setTimeout(refresh,500);return()=>{clearTimeout(timer);window.removeEventListener('load',refresh);observer.disconnect();document.removeEventListener('visibilitychange',visibility);ctx.revert()}},[signature,root]);}
function BrandWord(){return <span className="brand-word">Dolce <em>Look</em><small>BY JOSY</small></span>}
function Card({look,index=0,favorites,toggle}:{look:Look;index?:number;favorites:number[];toggle:(id:number)=>void}){return <article className={'product-card card-'+index%3}><div className="product-photo"><a href={`/look/${look.id}`} aria-label={`Conhecer ${look.name}`}><LookMedia look={look} key={`${look.id}:${look.img}`}/><span className="product-discover">Conhecer a peça <Icon/></span></a><button className={'save '+(favorites.includes(look.id)?'saved':'')} aria-label={`${favorites.includes(look.id)?'Remover':'Salvar'} ${look.name}`} aria-pressed={favorites.includes(look.id)} onClick={()=>toggle(look.id)}><Icon name="heart"/></button></div><div className="product-info"><a href={`/look/${look.id}`}><h3>{look.name}</h3><p>{look.type}{look.size?` · ${look.size}`:''}</p></a><span>{look.price!=null?look.price.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):<Icon/>}</span></div></article>}
export default function Storefront(){const {looks,loading,error,configured}=useInventory();const root=useRef<HTMLDivElement>(null),menu=useRef<HTMLDialogElement>(null);const[favorites,setFavorites]=useState<number[]>(()=>{try{const d=JSON.parse(localStorage.getItem('dolce-favorites')||'[]');return Array.isArray(d)?d.filter((n:unknown)=>Number.isInteger(n)):[]}catch{return[]}});const[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('Todos'),[sort,setSort]=useState('curadoria');const path=location.pathname.replace(/\/$/,'')||'/',isHome=path==='/',isCollection=path==='/colecao',isFavorites=path==='/favoritos',isBrand=path==='/a-marca',isContact=path==='/atendimento',productId=Number(path.match(/^\/look\/(\d+)$/)?.[1]);const product=looks.find(l=>l.id===productId);const saved=looks.filter(l=>favorites.includes(l.id));const featured=[looks[0],looks.find(l=>l.id===7)||looks[2],looks.find(l=>l.id===6)||looks[1]].filter(Boolean) as Look[];
 useChoreography(root,`${path}:${looks.map(l=>l.id).join(',')}`);
 useEffect(()=>{localStorage.setItem('dolce-favorites',JSON.stringify(favorites))},[favorites]);useEffect(()=>{if(configured&&!loading&&!error)setFavorites(p=>{const n=p.filter(id=>looks.some(l=>l.id===id));return n.length===p.length?p:n})},[looks,configured,loading,error]);
 useEffect(()=>{const names:Record<string,string>={'/':'Moda exclusiva','/colecao':'Coleção','/a-marca':'A marca','/atendimento':'Atendimento','/favoritos':'Minha seleção'};document.title=`${product?.name||names[path]||'Dolce Look'} — Dolce Look by Josy`},[path,product?.name]);
 function toggle(id:number){setFavorites(prev=>prev.includes(id)?prev.filter(n=>n!==id):[...prev,id]);setNotice(favorites.includes(id)?'Peça removida da seleção.':'Peça salva na sua seleção.')}
 const filtered=(isFavorites?saved:looks).filter(l=>(category==='Todos'||l.type===category)&&(`${l.name} ${l.desc}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')))).sort((a,b)=>sort==='nome'?a.name.localeCompare(b.name):a.id-b.id);
 const introMessage='Olá, Josy! Vim pelo site Dolce Look e quero conversar sobre os looks.';
 return <div className="site" ref={root}><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><header className="site-header"><a href="/" aria-label="Dolce Look, início"><BrandWord/></a><nav aria-label="Navegação principal">{[['/','Início'],['/colecao','Coleção'],['/a-marca','A marca'],['/atendimento','Atendimento']].map(([url,label])=><a key={url} href={url} aria-current={path===url?'page':undefined}>{label}</a>)}</nav><div className="header-tools"><a className="selection-link" href="/favoritos" aria-label={`Minha seleção, ${saved.length} peças`}><Icon name="heart"/><span>{saved.length.toString().padStart(2,'0')}</span></a><button className="menu-toggle" aria-label="Abrir menu" onClick={()=>menu.current?.showModal()}><Icon name="menu"/></button><a className="header-contact" href={wa(introMessage)} target="_blank" rel="noreferrer">Fale com a Josy <Icon/></a></div></header><dialog className="mobile-menu" ref={menu}><button className="menu-close" aria-label="Fechar menu" onClick={()=>menu.current?.close()}><Icon name="close"/></button><nav aria-label="Menu do celular">{[['/','Início'],['/colecao','Coleção'],['/a-marca','A marca'],['/atendimento','Atendimento'],['/favoritos','Minha seleção']].map(([u,n])=><a href={u} key={u}>{n}</a>)}</nav><p>Cuidando do seu look<br/>com bom gosto e estilo.</p></dialog><main id="conteudo">
 {isHome&&<><section className="cinema"><AtelierLight/><span className="atelier-word" aria-hidden="true">Dolce</span><div className="hero-glow" aria-hidden="true"/><div className="hero-headline"><h1><span className="line"><span>Seu estilo.</span></span><span className="line"><span><em className="luminous-type">Só seu.</em></span></span></h1></div><div className="hero-images"><a className="hero-frame left" href={looks[1]?`/look/${looks[1].id}`:'/colecao'}><Photo look={looks[1]} priority/></a><div className="hero-frame center"><HeroPhoto look={looks[0]} key={`${looks[0]?.id}:${looks[0]?.img}`}/></div><a className="hero-frame right" href={looks[6]?`/look/${looks[6].id}`:'/colecao'}><Photo look={looks[6]||looks[2]} priority/></a></div><div className="hero-promise"><p>Cuidando do seu look<br/>com bom gosto e estilo.</p><span>Peças exclusivas.<br/>Escolhas com personalidade.</span></div><div className="hero-after"><p>Uma peça.<br/><em>O seu momento.</em></p></div><div className="hero-bottom"><Button href="/colecao">Explore a coleção</Button><a className="scroll-label" href="#universo">Role para sentir a Dolce <Icon name="down"/></a><div className="scene-progress" aria-hidden="true"><span/></div></div></section><div className="fashion-ticker" aria-hidden="true"><div>{Array.from({length:8},(_,i)=><span key={i}>Dolce Look <b>·</b> Seu estilo, só seu <b>·</b></span>)}</div></div>
 <section className="universe" id="universo"><AtelierLight/><div className="universe-copy"><h2 className="word-flow">{'Mais que vestir. Um jeito de se reconhecer.'.split(' ').map((w,i)=><span className={i>=6?'outline-word':''} key={i}>{w} </span>)}</h2><p>Cor, textura e detalhes que fazem a diferença. A Dolce Look convida você a encontrar a composição que combina com o seu momento.</p><a className="underlined" href="/a-marca">Conheça a Dolce Look <Icon/></a></div><div className="universe-visual"><Photo look={looks[4]||looks[0]} className="universe-main parallax" motion={UNIVERSE_LOOK_VIDEOS_ENABLED}/><Photo look={looks[8]||looks[1]} className="universe-detail parallax" motion={UNIVERSE_LOOK_VIDEOS_ENABLED}/><span className="vertical-copy">BOM GOSTO & ESTILO</span></div></section>
 {featured.length>0&&<section className="wardrobe" aria-label="Looks em destaque">{featured.map((l,i)=><article className={'wardrobe-panel chapter-'+i} key={l.id}><div className="wardrobe-copy"><h2>{i===0?<>A cor que<br/><em>muda o dia.</em></>:i===1?<>Presença em<br/><em>cada passo.</em></>:<>Nos detalhes,<br/><em>você.</em></>}</h2><p>{l.desc}</p><a className="underlined" href={`/look/${l.id}`}>Explore {l.name.toLocaleLowerCase('pt-BR')} <Icon/></a><span className="wardrobe-position">{String(i+1).padStart(2,'0')} / {String(featured.length).padStart(2,'0')}</span></div><div className="wardrobe-image"><Photo look={l}/><div className="wardrobe-wash" aria-hidden="true"/></div><span className="wardrobe-ghost" aria-hidden="true">Dolce</span></article>)}</section>}
 <section className="home-collection" id="vitrine"><AtelierLight/><div className="section-top"><h2 data-reveal>Encontre a peça<br/>que é <em>você.</em></h2><div><p>Uma seleção para olhar de perto,<br/>salvar e conversar com a Josy.</p><a className="underlined" href="/colecao">Ver a coleção completa <Icon/></a></div></div><MagazineShelf looks={looks} favorites={favorites} toggle={toggle}/>{loading&&<p role="status">Carregando a coleção…</p>}{error&&<p role="alert">Não conseguimos atualizar a coleção. <button onClick={()=>location.reload()}>Tentar novamente</button></p>}</section>
 <section className="editorial"><AtelierLight/><div className="editorial-top"><h2>O olhar muda.<br/><em>O estilo permanece.</em></h2><p>Deslize pelos detalhes da Dolce Look.</p></div><div className="editorial-track">{looks.slice(3,8).map((l,i)=><a className={'editorial-frame frame-'+i%2} key={l.id} href={`/look/${l.id}`}><LookMedia look={l} key={`${l.id}:${l.img}`}/><span>{l.name}<Icon/></span></a>)}</div></section>
 <section className="josy-preview"><AtelierLight/><Photo look={looks[1]||looks[0]} className="parallax"/><div><h2 data-reveal>Seu look merece<br/><em>um olhar próximo.</em></h2><p>Salve o que chamou sua atenção. A Josy ajuda você a conferir os detalhes da peça, o tamanho e as possibilidades para o seu look.</p><Button href="/atendimento">Encontre seu próximo look</Button></div></section><ContactScene/></>}
 {(isCollection||isFavorites)&&<><section className="catalogue-intro"><AtelierLight/><div><h1>{isFavorites?<>Sua seleção.<br/><em>Seu olhar.</em></>:<>Um encontro<br/>com o seu <em>estilo.</em></>}</h1><p>{isFavorites?'Guarde suas escolhas e leve a seleção inteira para a Josy.':'Explore a coleção. Entre uma cor, uma textura e um detalhe, encontre o que combina com você.'}</p></div><Photo look={looks[8]||looks[0]} className="catalogue-cover parallax"/></section><section className="catalogue"><AtelierLight/><div className="catalogue-controls"><div className="categories" aria-label="Filtrar por categoria">{['Todos','Camisas','Blusas','Conjuntos','Vestidos'].map(c=><button key={c} className={c===category?'active':''} aria-pressed={c===category} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="catalogue-tools"><label><span className="sr-only">Buscar peças</span><input type="search" placeholder="Encontre uma peça" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span className="sr-only">Ordenar coleção</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="curadoria">Seleção Dolce</option><option value="nome">Nome: A a Z</option></select></label></div></div><div className="catalogue-state"><span>{filtered.length} peça{filtered.length!==1?'s':''}{isFavorites?' na sua seleção':''}</span><p>{configured?'A coleção acompanha a disponibilidade da loja.':'Consulte a Josy sobre a disponibilidade de cada peça.'}</p></div>{loading?<div className="catalogue-loading" role="status">Buscando as peças da coleção…</div>:error?<div className="empty-state" role="alert"><h2>Vamos tentar outra vez?</h2><p>Não foi possível atualizar a coleção.</p><button className="action" onClick={()=>location.reload()}>Atualizar coleção <Icon/></button></div>:filtered.length?<div className="product-grid">{filtered.map((l,i)=><Card favorites={favorites} toggle={toggle} look={l} key={l.id} index={i}/>)}</div>:<div className="empty-state"><h2>{isFavorites?'O seu olhar começa aqui.':'Uma nova escolha espera por você.'}</h2><p>{isFavorites?'Toque no coração das peças para guardar as suas favoritas.':'Nenhuma peça nesta busca. Explore as outras categorias.'}</p>{isFavorites?<Button href="/colecao">Descobrir a coleção</Button>:<button className="action" onClick={()=>{setCategory('Todos');setQuery('')}}>Ver todas as peças <Icon/></button>}</div>}{isFavorites&&saved.length>0&&<div className="selection-send"><p>Gostou dessas escolhas?</p><Button href={wa('Olá, Josy! Separei estes looks da Dolce Look: '+saved.map(l=>l.name).join('; ')+'. Pode me informar valores, tamanhos e disponibilidade?')}>Enviar {saved.length} peça{saved.length>1?'s':''} para a Josy</Button></div>}</section><ContactScene/></>}
 {isBrand&&<><section className="brand-intro"><AtelierLight/><h1>Bom gosto.<br/>Estilo.<br/><em>O seu jeito.</em></h1><Photo look={looks[1]||looks[0]} className="brand-portrait parallax"/><p>Dolce Look by Josy</p></section><section className="brand-story"><AtelierLight/><h2 className="word-flow">{'A moda ganha sentido quando tem a ver com você.'.split(' ').map((w,i)=><span key={i}>{w} </span>)}</h2><div className="brand-story-copy"><p>“Cuidando do seu look com bom gosto e estilo.” A frase da Dolce Look guia a experiência: descobrir peças, olhar os detalhes e escolher com personalidade.</p><p>Camisas, rendas, vestidos e composições que abrem espaço para o seu próprio jeito de vestir. Cada look apresentado aqui pode ser explorado de perto e compartilhado com a Josy.</p><a className="underlined" href="/colecao">Entre na coleção <Icon/></a></div></section><section className="brand-diptych"><AtelierLight/><Photo look={looks[4]||looks[0]} className="parallax"/><div><h2>O detalhe<br/>faz o <em>encontro.</em></h2><Photo look={looks[8]||looks[1]} className="parallax"/></div></section><section className="brand-service"><AtelierLight/><h2>Uma escolha<br/><em>com cuidado.</em></h2><div><p>A coleção é feita de peças exclusivas. Antes de decidir, converse com a Josy para confirmar disponibilidade, medidas e valor.</p><p>Você pode enviar uma peça ou toda a sua seleção pelo WhatsApp. O atendimento começa pelo que chamou a sua atenção.</p><Button href="/atendimento">Converse com a Josy</Button></div></section><ContactScene/></>}
 {isContact&&<><section className="contact-intro"><AtelierLight/><div><h1>Vamos cuidar<br/>do seu <em>look?</em></h1><p>Conte para a Josy o que você gostou. Uma cor, uma peça ou a seleção inteira: a conversa começa do seu jeito.</p><Button href={wa(introMessage)}>Iniciar conversa no WhatsApp</Button><a className="phone-link" href="tel:+5535998290565">(35) 99829-0565</a></div><Photo look={looks[0]} className="contact-photo parallax"/></section><section className="service-steps"><AtelierLight/><h2>Do primeiro olhar<br/>à <em>sua escolha.</em></h2><ol><li><h3>Explore</h3><p>Conheça as peças e abra os detalhes dos looks que têm a ver com você.</p></li><li><h3>Salve</h3><p>Toque no coração para reunir suas escolhas em uma seleção só sua.</p></li><li><h3>Converse</h3><p>Envie sua seleção. A Josy confirma medidas, valores e disponibilidade.</p></li></ol></section><section className="faq"><AtelierLight/><h2>Antes de<br/><em>escolher.</em></h2><div>{[['Como consultar o tamanho e o valor?','Abra a página da peça e toque em “Quero essa peça”. A mensagem já leva o nome do look para a Josy confirmar medidas e valor.'],['As peças são exclusivas?','Sim. A Dolce Look trabalha com uma unidade de cada peça. Confirme a disponibilidade com a Josy antes de fechar sua escolha.'],['Posso enviar mais de um look?','Pode. Salve as peças no coração e abra “Minha seleção” para enviar todas de uma vez pelo WhatsApp.'],['Como combinar entrega ou retirada?','Converse com a Josy no atendimento para confirmar as opções para você. As condições são combinadas antes da compra.']].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section><ContactScene/></>}
 {productId>0&&<>{loading?<section className="empty-state" role="status"><h1>Buscando sua peça…</h1></section>:error?<section className="empty-state" role="alert"><h1>Não conseguimos atualizar esta peça.</h1><button className="action" onClick={()=>location.reload()}>Tentar novamente <Icon/></button></section>:product?<><section className="product-detail"><AtelierLight/><a className="back-link" href="/colecao">Voltar à coleção</a><div className="detail-layout"><Photo look={product} className="detail-photo" priority/><div className="detail-content"><h1>{product.name}</h1><p className="detail-type">{product.type}</p><p className="detail-description">{product.desc}</p>{product.price!=null&&<p className="detail-price">{product.price.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p>}<dl><div><dt>Peça</dt><dd>Exclusiva · uma unidade</dd></div>{product.size&&<div><dt>Tamanho</dt><dd>{product.size}</dd></div>}<div><dt>Atendimento</dt><dd>Direto com a Josy</dd></div></dl><Button href={wa(`Olá, Josy! Gostei do look ${product.name} no site Dolce Look. Pode me confirmar medidas, valor e disponibilidade?`)}>Quero essa peça</Button><button className="detail-save" aria-pressed={favorites.includes(product.id)} onClick={()=>toggle(product.id)}><Icon name="heart"/>{favorites.includes(product.id)?'Salva na sua seleção':'Salvar na minha seleção'}</button><p className="detail-note">Confirme tamanho, valor e disponibilidade antes de concluir sua escolha.</p></div></div></section><section className="related"><AtelierLight/><div className="section-top"><h2>Continue o<br/><em>seu olhar.</em></h2><a className="underlined" href="/colecao">Coleção completa <Icon/></a></div><div className="product-grid">{looks.filter(l=>l.id!==product.id).slice(0,3).map((l,i)=><Card favorites={favorites} toggle={toggle} key={l.id} look={l} index={i}/>)}</div></section></>:<section className="empty-state"><h1>Essa peça já<br/>seguiu seu <em>caminho.</em></h1><p>Ela não está disponível na coleção atual. Explore outras escolhas ou fale com a Josy.</p><Button href="/colecao">Descobrir outras peças</Button></section>}</>}
 {!isHome&&!isBrand&&!isContact&&!isCollection&&!isFavorites&&!productId&&<section className="empty-state"><h1>Vamos voltar<br/>à <em>Dolce?</em></h1><p>Essa página não foi encontrada.</p><Button href="/">Voltar ao início</Button></section>}
 </main><footer className="site-footer"><AtelierLight/><div className="footer-brand"><BrandWord/><p>Cuidando do seu look<br/>com bom gosto e estilo.</p></div><nav aria-label="Navegação no rodapé"><a href="/colecao">Coleção</a><a href="/a-marca">A marca</a><a href="/atendimento">Atendimento</a><a href="/favoritos">Minha seleção</a></nav><div className="footer-social"><a href="https://www.instagram.com/dolce_lookk/" target="_blank" rel="noreferrer">Instagram <Icon/></a><a href={wa(introMessage)} target="_blank" rel="noreferrer">WhatsApp <Icon/></a></div><div className="footer-bottom"><span>Dolce Look by Josy</span><a href="/admin">Área da loja</a></div></footer><a className="floating-wa" href={wa(introMessage)} target="_blank" rel="noreferrer" aria-label="Conversar com a Josy pelo WhatsApp"><Icon name="whatsapp"/></a><p className="sr-only" role="status" aria-live="polite">{notice}</p></div>}
function ContactScene(){return <section className="contact-scene expand-panel"><AtelierLight/><div className="contact-arc" aria-hidden="true"/><h2>Seu próximo look<br/>começa com <em className="luminous-type">você.</em></h2><Button light href={wa('Olá, Josy! Vim pelo site Dolce Look e quero encontrar meu próximo look.')}>Encontre seu look com a Josy</Button><a className="scene-secondary" href="/atendimento">Conheça o atendimento</a><span className="scene-signature" aria-hidden="true">by Josy</span></section>}

function AtelierLight(){return <div className="atelier-light" aria-hidden="true"><span/><span/></div>}
